// HOME PRODUCTS TYPES
export const FETCH_HOME_PRODUCTS_REQUEST = 'FETCH_HOME_PRODUCTS_REQUEST';
export const FETCH_HOME_PRODUCTS_SUCCESS = 'FETCH_HOME_PRODUCTS_SUCCESS';
export const FETCH_HOME_PRODUCTS_ERROR = 'FETCH_HOME_PRODUCTS_ERROR';

// PRESCRIPTION UPLOAD TYPES
export const PRESCRIPTION_UPLOAD_REQUEST = 'PRESCRIPTION_UPLOAD_REQUEST';
export const PRESCRIPTION_UPLOAD_SUCCESS = 'PRESCRIPTION_UPLOAD_SUCCESS';
export const PRESCRIPTION_UPLOAD_ERROR = 'PRESCRIPTION_UPLOAD_ERROR';
export const PRESCRIPTION_UPLOAD_SUCCESS_COMPLETE =
  'PRESCRIPTION_UPLOAD_SUCCESS_COMPLETE';
export const PRESCRIPTION_UPLOAD_FINISHED = 'PRESCRIPTION_UPLOAD_FINISHED';

// SHOP PRODUCTS TYPES
export const FETCH_SHOP_PRODUCTS_REQUEST = 'FETCH_SHOP_PRODUCTS_REQUEST';
export const FETCH_SHOP_PRODUCTS_SUCCESS = 'FETCH_SHOP_PRODUCTS_SUCCESS';
export const FETCH_SHOP_PRODUCTS_ERROR = 'FETCH_SHOP_PRODUCTS_ERROR';

// SHOP PRODUCT DETAILS TYPES
export const FETCH_PRODUCT_DETAILS_REQUEST = 'FETCH_PRODUCT_DETAILS_REQUEST';
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_ERROR = 'FETCH_PRODUCT_DETAILS_ERROR';

// GET USER INFO (CHECKOUT PAGE) TYPES
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';
export const GET_USER_AREAS = 'GET_USER_AREAS';

// VENDOR DETAILS TYPES
export const FETCH_VENDOR_DETAILS_REQUEST = 'FETCH_VENDOR_DETAILS_REQUEST';
export const FETCH_VENDOR_DETAILS_SUCCESS = 'FETCH_VENDOR_DETAILS_SUCCESS';
export const FETCH_VENDOR_DETAILS_ERROR = 'FETCH_VENDOR_DETAILS_ERROR';

// SHOP LIST TYPES
export const FETCH_SHOP_LIST_REQUEST = 'FETCH_SHOP_LIST_REQUEST';
export const FETCH_SHOP_LIST_SUCCESS = 'FETCH_SHOP_LIST_SUCCESS';
export const FETCH_SHOP_LIST_ERROR = 'FETCH_SHOP_LIST_ERROR';

// CATEGORY FETCH TYPES
export const FETCH_CATEGORIES = 'FETCH_SHOP_LIST_REQUEST';
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const GET_CHILD_CATEGORY = 'GET_CHILD_CATEGORY';

// FILTER PRODUCTS TYPES
export const FILTER_PRODUCTS_BY_SIZE = 'FILTER_PRODUCTS_BY_SIZE';
export const FILTER_PRODUCTS_BY_PRICE = 'FILTER_PRODUCTS_BY_PRICE';
export const SHOW_PRODUCTS_BY_NUMBER = 'SHOW_PRODUCTS_BY_NUMBER';

// ADD-REMOVE TO BASKET
export const ADD_TO_SERVER_BASKET_REQUEST = 'ADD_TO_SERVER_BASKET_REQUEST';
export const ADD_TO_SERVER_BASKET_SUCCESS = 'ADD_TO_SERVER_BASKET_SUCCESS';
export const ADD_TO_BASKET_SUCCESS = 'ADD_TO_BASKET_SUCCESS';
export const ADD_TO_BASKET_REQUEST = 'ADD_TO_BASKET_REQUEST';
export const ADD_TO_BASKET_ERROR = 'ADD_TO_BASKET_ERROR';
export const BASKET_STATUS_SUCCESS = 'BASKET_STATUS_SUCCESS';
export const BASKET_STATUS_COMPLETE = 'BASKET_STATUS_COMPLETE';
export const LOCAL_BASKET_MSG = 'LOCAL_BASKET_MSG';

// ADD-REMOVE TO BASKET
export const GET_CART_ITEM_REQUEST = 'GET_CART_ITEM_REQUEST';
export const GET_CART_ITEM_SUCCESS = 'GET_CART_ITEM_SUCCESS';
export const GET_CART_ITEM_ERROR = 'GET_CART_ITEM_ERROR';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';

// GET CART ID
export const GET_CART_UPDATE_ID = 'GET_CART_UPDATE_ID';
export const REMOVE_CART_UPDATE_ID = 'REMOVE_CART_UPDATE_ID';

// ADD CART ANIMATION
export const PRODUCT_ADD_CLEAR = 'PRODUCT_ADD_CLEAR';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_ADD_FINISH = 'PRODUCT_ADD_FINISH';

// ADD-REMOVE TO WISH LIST
export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_ONLINE_WISHLIST_SUCCESS = 'ADD_TO_ONLINE_WISHLIST_SUCCESS';
export const ADD_TO_LOCAL_WISHLIST_SUCCESS = 'ADD_TO_LOCAL_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_ERROR = 'ADD_TO_WISHLIST_ERROR';
export const REMOVE_FROM_ONLINE_WISHLIST = 'REMOVE_FROM_ONLINE_WISHLIST';
export const REMOVE_FROM_LOCAL_WISHLIST = 'REMOVE_FROM_LOCAL_WISHLIST';
export const WISHCART_STATUS_SUCCESS = 'WISHCART_STATUS_SUCCESS';
export const WISHCART_STATUS_COMPLETE = 'WISHCART_STATUS_COMPLETE';
export const ADD_TO_WISHCART_MSG = 'ADD_TO_WISHCART_MSG';
// GET WISHLIST ITEMS
export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_ERROR = 'GET_WISHLIST_ERROR';

// ADD-REMOVE TO COMPARE
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE';

// ADD-REMOVE TO COMPARE
export const SHOW_QUICK_DES = 'SHOW_QUICK_DES';
export const REMOVE_QUICK_DES = 'REMOVE_QUICK_DES';

// GET PRODUCT SUGGETIONS
export const GET_PRODUCT_SUGGETIONS = 'GET_PRODUCT_SUGGETIONS';
export const FAILED_PRODUCT_SUGGETIONS = 'FAILED_PRODUCT_SUGGETIONS';

// SEARCH PRODUCTS ACTION
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';

// SIGN UP ACTION
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

// USER ACTION
export const SET_USER = 'SET_USER';
export const SET_USER_NULL = 'SET_USER_NULL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// LOGIN ACTION
export const USER_ACTIVITY_SUCCESS = 'USER_ACTIVITY_SUCCESS';
export const USER_ACTIVITY_ERROR = 'USER_ACTIVITY_ERROR';

// LOGOUT ACTION
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

// OTP ACTION
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_ERROR = 'OTP_ERROR';

// NUMBER AVAILABLE ACTION
export const NUMBER_AVAILABLE_REQUEST = 'NUMBER_AVAILABLE_REQUEST';
export const NUMBER_AVAILABLE_SUCCESS = 'NUMBER_AVAILABLE_SUCCESS';
export const NUMBER_AVAILABLE_ERROR = 'NUMBER_AVAILABLE_ERROR';
// DASHBOARD DATA ACTION
export const DASHBOARD_DATA_LOADING = 'DASHBOARD_DATA_LOADING';
export const DASHBOARD_DATA_SUCCESS = 'DASHBOARD_DATA_SUCCESS';
export const DASHBOARD_DATA_ERROR = 'DASHBOARD_DATA_ERROR';
// DASHBOARD ACCOUNT INFORMATION ACTION
export const ACCOUNT_INFO_SUBMIT_REQUEST = 'ACCOUNT_INFO_SUBMIT_REQUEST';
export const ACCOUNT_INFO_SUBMIT_SUCCESS = 'ACCOUNT_INFO_SUBMIT_SUCCESS';
export const ACCOUNT_INFO_SUBMIT_ERROR = 'ACCOUNT_INFO_SUBMIT_ERROR';
export const ACCOUNT_INFO_SUBMIT_SUCCESS_RESPONSE_CLEAR =
  'ACCOUNT_INFO_SUBMIT_SUCCESS_RESPONSE_CLEAR';

// MAKE ORDER ACTION
export const MAKE_ORDER_REQUEST = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_ERROR = 'MAKE_ORDER_ERROR';

// SEND MESSAGE ACTION

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const SEND_MESSAGE_RESPONSE_CLEAR = 'SEND_MESSAGE_RESPONSE_CLEAR';

// CHECK CART PRODUCTS ACTION
export const CART_CHECK_REQUEST = 'CART_CHECK_REQUEST';
export const CART_CHECK_SUCCESS = 'CART_CHECK_SUCCESS';
export const CART_CHECK_ERROR = 'CART_CHECK_ERROR';

// CHECKOUT FINAL PRODUCTS
export const ADD_TO_CHECKOUT = 'ADD_TO_CHECKOUT';

// GET ALL CITIES,THANA,UNION
export const DISTRICTS_ADD_SUCCESS = 'DISTRICTS_ADD_SUCCESS';
export const THANA_ADD_SUCCESS = 'THANA_ADD_SUCCESS';
export const UNION_ADD_SUCCESS = 'UNION_ADD_SUCCESS';

// GET ALL SHIIPPING ADDRESS
export const SHIPPING_ADDRESS_REQUEST = 'SHIPPING_ADDRESS_REQUEST';
export const SHIPPING_ADDRESS_SUCCESS = 'SHIPPING_ADDRESS_SUCCESS';
export const SHIPPING_ADDRESS_EORROR = 'SHIPPING_ADDRESS_EORROR';
export const SET_SHIPPING_ID_SUCCESS = 'SET_SHIPPING_ID_SUCCESS';

// MAKE ORDER
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR';
export const PLACE_ORDER_COMPLETE = 'PLACE_ORDER_COMPLETE';

// SINGLE COMPANY PRODUCTS
export const SINGLE_BRAND_PRODUCT_REQUEST = 'SINGLE_BRAND_PRODUCT_REQUEST';
export const SINGLE_BRAND_PRODUCT_SUCCESS = 'SINGLE_BRAND_PRODUCT_SUCCESS';
export const SINGLE_BRAND_PRODUCT_ERROR = 'SINGLE_BRAND_PRODUCT_ERROR';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

// GET ORDER LIST
export const GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_ERROR = 'GET_ORDER_LIST_ERROR';

// NECCESSARY ALL PRODUCTS
export const NECCESSARY_PRODUCTS_REQUEST = 'NECCESSARY_PRODUCTS_REQUEST';
export const NECCESSARY_PRODUCTS_SUCCESS = 'NECCESSARY_PRODUCTS_SUCCESS';
export const NECCESSARY_PRODUCTS_ERROR = 'NECCESSARY_PRODUCTS_ERROR';
export const FILTER_NECCESSARY_PRODUCTS = 'FILTER_NECCESSARY_PRODUCTS';

// GENERIC ALL PRODUCTS
export const GENERIC_PRODUCTS_REQUEST = 'GENERIC_PRODUCTS_REQUEST';
export const GENERIC_PRODUCTS_SUCCESS = 'GENERIC_PRODUCTS_SUCCESS';
export const GENERIC_PRODUCTS_ERROR = 'GENERIC_PRODUCTS_ERROR';
export const FILTER_GENERIC_PRODUCTS = 'FILTER_GENERIC_PRODUCTS';

// GET BLOG LIST
export const GET_BLOGLIST_REQUEST = 'GET_BLOGLIST_REQUEST';
export const GET_BLOGLIST_SUCCESS = 'GET_BLOGLIST_SUCCESS';
export const GET_BLOGLIST_ERROR = 'GET_BLOGLIST_ERROR';

// GET SINGLE BLOG
export const GET_SINGLEBLOG_REQUEST = 'GET_SINGLEBLOG_REQUEST';
export const GET_SINGLEBLOG_SUCCESS = 'GET_SINGLEBLOG_SUCCESS';
export const GET_SINGLEBLOG_ERROR = 'GET_SINGLEBLOG_ERROR';

// GET SINGLE ORDER
export const SINGLE_ORDER_ERROR = 'SINGLE_ORDER_ERROR';
export const SINGLE_ORDER_REQUEST = 'SINGLE_ORDER_REQUEST';
export const SINGLE_ORDER_SUCCESS = 'SINGLE_ORDER_SUCCESS';

// GET OTHER BRANDS
export const OTHER_BRAND_REQUEST = 'OTHER_BRAND_REQUEST';
export const OTHER_BRAND_SUCCESS = 'OTHER_BRAND_SUCCESS';
export const OTHER_BRAND_ERROR = 'OTHER_BRAND_ERROR';

// GET CATGORYBASED PRODUCTS
export const CATEGORY_BASED_REQUEST = 'CATEGORY_BASED_REQUEST';
export const CATEGORY_BASED_SUCCESS = 'CATEGORY_BASED_SUCCESS';
export const CATEGORY_BASED_ERROR = 'CATEGORY_BASED_ERROR';
