export const products = [
  {
    id: 1,
    photo: '01.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 2,
    photo: '02.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: '14948754.00',
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 3,
    photo: '03.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 4,
    photo: '04.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 5,
    photo: '05.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 6,
    photo: '06.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 7,
    photo: '07.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 8,
    photo: '01.png',
    name: 'Omron HEM 7120 Fully Automatic-100mg',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
];
const campOne = [
  {
    id: 1,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
  {
    id: 2,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
  {
    id: 3,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
  {
    id: 4,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
  {
    id: 5,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
  {
    id: 6,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
  {
    id: 7,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
  {
    id: 8,
    photo: `./uparzonassets/uparzonimages/campaigncards/camp02.png`,
    name: `campaign 1`,
  },
];
